#include <any>
#include <string>
#include <unordered_map>
#include <vector>
using CSValueMap = std::unordered_map<std::string, std::any>;
inline auto inputdata = std::vector<CSValueMap>{
    CSValueMap{{std::string(R"(selfInfo)"),
                CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                   {std::string(R"(damageLevel)"), uint16_t(0)},
                                                                   {std::string(R"(side)"), uint16_t(0)},
                                                                   {std::string(R"(type)"), uint16_t(0)}}},
                           {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                   {std::string(R"(y)"), double(0.000000)},
                                                                   {std::string(R"(z)"), double(0.000000)}}},
                           {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                   {std::string(R"(y)"), double(0.000000)},
                                                                   {std::string(R"(z)"), double(0.000000)}}}}},
               {std::string(R"(scannedInfo)"), std::vector<std::any>{}},
               {std::string(R"(roll)"), double(0.000000)},
               {std::string(R"(weaponinfo)"), std::vector<std::any>{}},
               {std::string(R"(pitch)"), double(0.000000)},
               {std::string(R"(yaw)"), double(0.000000)}},
    CSValueMap{{std::string(R"(selfInfo)"),
                CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                   {std::string(R"(damageLevel)"), uint16_t(0)},
                                                                   {std::string(R"(side)"), uint16_t(1)},
                                                                   {std::string(R"(type)"), uint16_t(0)}}},
                           {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                   {std::string(R"(y)"), double(0.000000)},
                                                                   {std::string(R"(z)"), double(0.000000)}}},
                           {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                   {std::string(R"(y)"), double(0.000000)},
                                                                   {std::string(R"(z)"), double(-0.000000)}}}}},
               {std::string(R"(scannedInfo)"), std::vector<std::any>{}},
               {std::string(R"(roll)"), double(0.000000)},
               {std::string(R"(weaponinfo)"),
                std::vector<std::any>{CSValueMap{{std::string(R"(ammo)"), int32_t(30)},
                                                 {std::string(R"(reloadingState)"), double(0.000000)},
                                                 {std::string(R"(weaponName)"), std::string(R"(125mmHE)")},
                                                 {std::string(R"(direction)"), double(0.000000)},
                                                 {std::string(R"(range)"), double(5000.000000)}}}},
               {std::string(R"(pitch)"), double(0.000000)},
               {std::string(R"(yaw)"), double(-90.000000)}},
    CSValueMap{{std::string(R"(selfInfo)"),
                CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                   {std::string(R"(damageLevel)"), uint16_t(0)},
                                                                   {std::string(R"(side)"), uint16_t(1)},
                                                                   {std::string(R"(type)"), uint16_t(0)}}},
                           {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                   {std::string(R"(y)"), double(0.000000)},
                                                                   {std::string(R"(z)"), double(0.000000)}}},
                           {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                   {std::string(R"(y)"), double(0.000000)},
                                                                   {std::string(R"(z)"), double(-0.000000)}}}}},
               {std::string(R"(scannedInfo)"),
                std::vector<std::any>{
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(1)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                       {std::string(R"(y)"), double(0.000000)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                       {std::string(R"(y)"), double(0.000000)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}},
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(1)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(2)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                       {std::string(R"(y)"), double(0.000000)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(5550.000000)},
                                                                       {std::string(R"(y)"), double(4546.293846)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}}}},
               {std::string(R"(roll)"), double(0.000000)},
               {std::string(R"(weaponinfo)"),
                std::vector<std::any>{CSValueMap{{std::string(R"(ammo)"), int32_t(30)},
                                                 {std::string(R"(reloadingState)"), double(0.000000)},
                                                 {std::string(R"(weaponName)"), std::string(R"(125mmHE)")},
                                                 {std::string(R"(direction)"), double(0.000000)},
                                                 {std::string(R"(range)"), double(5000.000000)}}}},
               {std::string(R"(pitch)"), double(0.000000)},
               {std::string(R"(yaw)"), double(-90.000000)}},
    CSValueMap{{std::string(R"(selfInfo)"),
                CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                   {std::string(R"(damageLevel)"), uint16_t(0)},
                                                                   {std::string(R"(side)"), uint16_t(1)},
                                                                   {std::string(R"(type)"), uint16_t(0)}}},
                           {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                   {std::string(R"(y)"), double(0.000000)},
                                                                   {std::string(R"(z)"), double(0.000000)}}},
                           {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                   {std::string(R"(y)"), double(0.000000)},
                                                                   {std::string(R"(z)"), double(-0.000000)}}}}},
               {std::string(R"(scannedInfo)"),
                std::vector<std::any>{
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(1)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                       {std::string(R"(y)"), double(0.000000)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                       {std::string(R"(y)"), double(0.000000)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}},
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(1)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(2)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                       {std::string(R"(y)"), double(0.000000)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(5550.000000)},
                                                                       {std::string(R"(y)"), double(4546.293846)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}}}},
               {std::string(R"(roll)"), double(0.000000)},
               {std::string(R"(weaponinfo)"),
                std::vector<std::any>{CSValueMap{{std::string(R"(ammo)"), int32_t(30)},
                                                 {std::string(R"(reloadingState)"), double(0.000000)},
                                                 {std::string(R"(weaponName)"), std::string(R"(125mmHE)")},
                                                 {std::string(R"(direction)"), double(0.000000)},
                                                 {std::string(R"(range)"), double(5000.000000)}}}},
               {std::string(R"(pitch)"), double(0.000000)},
               {std::string(R"(yaw)"), double(-90.000000)}},
    CSValueMap{{std::string(R"(selfInfo)"),
                CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                   {std::string(R"(damageLevel)"), uint16_t(0)},
                                                                   {std::string(R"(side)"), uint16_t(1)},
                                                                   {std::string(R"(type)"), uint16_t(0)}}},
                           {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.150000)},
                                                                   {std::string(R"(y)"), double(0.000000)},
                                                                   {std::string(R"(z)"), double(0.000000)}}},
                           {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                   {std::string(R"(y)"), double(0.000000)},
                                                                   {std::string(R"(z)"), double(-0.000000)}}}}},
               {std::string(R"(scannedInfo)"),
                std::vector<std::any>{
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(1)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                       {std::string(R"(y)"), double(0.000000)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                       {std::string(R"(y)"), double(0.000000)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}},
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(1)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(2)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                       {std::string(R"(y)"), double(0.000000)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(5550.000000)},
                                                                       {std::string(R"(y)"), double(4546.293846)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}}}},
               {std::string(R"(roll)"), double(0.000000)},
               {std::string(R"(weaponinfo)"),
                std::vector<std::any>{CSValueMap{{std::string(R"(ammo)"), int32_t(30)},
                                                 {std::string(R"(reloadingState)"), double(0.000000)},
                                                 {std::string(R"(weaponName)"), std::string(R"(125mmHE)")},
                                                 {std::string(R"(direction)"), double(0.000000)},
                                                 {std::string(R"(range)"), double(5000.000000)}}}},
               {std::string(R"(pitch)"), double(0.000000)},
               {std::string(R"(yaw)"), double(-90.000000)}},
    CSValueMap{{std::string(R"(selfInfo)"),
                CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                   {std::string(R"(damageLevel)"), uint16_t(0)},
                                                                   {std::string(R"(side)"), uint16_t(1)},
                                                                   {std::string(R"(type)"), uint16_t(0)}}},
                           {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.300000)},
                                                                   {std::string(R"(y)"), double(0.000008)},
                                                                   {std::string(R"(z)"), double(0.000000)}}},
                           {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.007500)},
                                                                   {std::string(R"(y)"), double(0.000000)},
                                                                   {std::string(R"(z)"), double(-0.000000)}}}}},
               {std::string(R"(scannedInfo)"),
                std::vector<std::any>{
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(1)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.150000)},
                                                                       {std::string(R"(y)"), double(0.000000)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.000000)},
                                                                       {std::string(R"(y)"), double(0.000000)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}},
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(1)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(2)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.150000)},
                                                                       {std::string(R"(y)"), double(0.000000)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(5550.000000)},
                                                                       {std::string(R"(y)"), double(4546.293846)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}}}},
               {std::string(R"(roll)"), double(0.000000)},
               {std::string(R"(weaponinfo)"),
                std::vector<std::any>{CSValueMap{{std::string(R"(ammo)"), int32_t(30)},
                                                 {std::string(R"(reloadingState)"), double(0.000000)},
                                                 {std::string(R"(weaponName)"), std::string(R"(125mmHE)")},
                                                 {std::string(R"(direction)"), double(0.000026)},
                                                 {std::string(R"(range)"), double(5000.000000)}}}},
               {std::string(R"(pitch)"), double(0.000000)},
               {std::string(R"(yaw)"), double(-89.998500)}},
    CSValueMap{{std::string(R"(selfInfo)"),
                CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                   {std::string(R"(damageLevel)"), uint16_t(0)},
                                                                   {std::string(R"(side)"), uint16_t(1)},
                                                                   {std::string(R"(type)"), uint16_t(0)}}},
                           {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.450000)},
                                                                   {std::string(R"(y)"), double(0.000059)},
                                                                   {std::string(R"(z)"), double(0.000000)}}},
                           {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.022500)},
                                                                   {std::string(R"(y)"), double(0.000000)},
                                                                   {std::string(R"(z)"), double(-0.000000)}}}}},
               {std::string(R"(scannedInfo)"),
                std::vector<std::any>{
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(1)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.300000)},
                                                                       {std::string(R"(y)"), double(0.000008)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.007500)},
                                                                       {std::string(R"(y)"), double(0.000000)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}},
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(1)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(2)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.300000)},
                                                                       {std::string(R"(y)"), double(-0.000008)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(5550.007500)},
                                                                       {std::string(R"(y)"), double(4546.293846)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}}}},
               {std::string(R"(roll)"), double(0.000000)},
               {std::string(R"(weaponinfo)"),
                std::vector<std::any>{CSValueMap{{std::string(R"(ammo)"), int32_t(30)},
                                                 {std::string(R"(reloadingState)"), double(0.000000)},
                                                 {std::string(R"(weaponName)"), std::string(R"(125mmHE)")},
                                                 {std::string(R"(direction)"), double(0.000131)},
                                                 {std::string(R"(range)"), double(5000.000000)}}}},
               {std::string(R"(pitch)"), double(0.000000)},
               {std::string(R"(yaw)"), double(-89.992499)}},
    CSValueMap{{std::string(R"(selfInfo)"),
                CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                   {std::string(R"(damageLevel)"), uint16_t(0)},
                                                                   {std::string(R"(side)"), uint16_t(1)},
                                                                   {std::string(R"(type)"), uint16_t(0)}}},
                           {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.600000)},
                                                                   {std::string(R"(y)"), double(0.000220)},
                                                                   {std::string(R"(z)"), double(0.000000)}}},
                           {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.045000)},
                                                                   {std::string(R"(y)"), double(0.000003)},
                                                                   {std::string(R"(z)"), double(-0.000000)}}}}},
               {std::string(R"(scannedInfo)"),
                std::vector<std::any>{
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(1)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.450000)},
                                                                       {std::string(R"(y)"), double(0.000059)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.022500)},
                                                                       {std::string(R"(y)"), double(0.000000)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}},
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(1)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(2)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.450000)},
                                                                       {std::string(R"(y)"), double(-0.000059)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(5550.022500)},
                                                                       {std::string(R"(y)"), double(4546.293845)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}}}},
               {std::string(R"(roll)"), double(0.000000)},
               {std::string(R"(weaponinfo)"),
                std::vector<std::any>{CSValueMap{{std::string(R"(ammo)"), int32_t(30)},
                                                 {std::string(R"(reloadingState)"), double(0.000000)},
                                                 {std::string(R"(weaponName)"), std::string(R"(125mmHE)")},
                                                 {std::string(R"(direction)"), double(0.000367)},
                                                 {std::string(R"(range)"), double(5000.000000)}}}},
               {std::string(R"(pitch)"), double(0.000000)},
               {std::string(R"(yaw)"), double(-89.978989)}},
    CSValueMap{{std::string(R"(selfInfo)"),
                CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                   {std::string(R"(damageLevel)"), uint16_t(0)},
                                                                   {std::string(R"(side)"), uint16_t(1)},
                                                                   {std::string(R"(type)"), uint16_t(0)}}},
                           {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.750000)},
                                                                   {std::string(R"(y)"), double(0.000590)},
                                                                   {std::string(R"(z)"), double(0.000000)}}},
                           {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.075000)},
                                                                   {std::string(R"(y)"), double(0.000014)},
                                                                   {std::string(R"(z)"), double(-0.000000)}}}}},
               {std::string(R"(scannedInfo)"),
                std::vector<std::any>{
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(1)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.600000)},
                                                                       {std::string(R"(y)"), double(0.000220)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.045000)},
                                                                       {std::string(R"(y)"), double(0.000003)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}},
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(1)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(2)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.600000)},
                                                                       {std::string(R"(y)"), double(-0.000220)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(5550.045000)},
                                                                       {std::string(R"(y)"), double(4546.293842)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}}}},
               {std::string(R"(roll)"), double(0.000000)},
               {std::string(R"(weaponinfo)"),
                std::vector<std::any>{CSValueMap{{std::string(R"(ammo)"), int32_t(30)},
                                                 {std::string(R"(reloadingState)"), double(0.000000)},
                                                 {std::string(R"(weaponName)"), std::string(R"(125mmHE)")},
                                                 {std::string(R"(direction)"), double(0.000786)},
                                                 {std::string(R"(range)"), double(5000.000000)}}}},
               {std::string(R"(pitch)"), double(0.000000)},
               {std::string(R"(yaw)"), double(-89.954955)}},
    CSValueMap{{std::string(R"(selfInfo)"),
                CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                   {std::string(R"(damageLevel)"), uint16_t(0)},
                                                                   {std::string(R"(side)"), uint16_t(1)},
                                                                   {std::string(R"(type)"), uint16_t(0)}}},
                           {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.899999)},
                                                                   {std::string(R"(y)"), double(0.001298)},
                                                                   {std::string(R"(z)"), double(0.000000)}}},
                           {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.112500)},
                                                                   {std::string(R"(y)"), double(0.000044)},
                                                                   {std::string(R"(z)"), double(-0.000000)}}}}},
               {std::string(R"(scannedInfo)"),
                std::vector<std::any>{
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(1)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.750000)},
                                                                       {std::string(R"(y)"), double(0.000590)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.075000)},
                                                                       {std::string(R"(y)"), double(0.000014)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}},
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(1)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(2)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.750000)},
                                                                       {std::string(R"(y)"), double(-0.000590)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(5550.075000)},
                                                                       {std::string(R"(y)"), double(4546.293831)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}}}},
               {std::string(R"(roll)"), double(0.000000)},
               {std::string(R"(weaponinfo)"),
                std::vector<std::any>{CSValueMap{{std::string(R"(ammo)"), int32_t(30)},
                                                 {std::string(R"(reloadingState)"), double(0.000000)},
                                                 {std::string(R"(weaponName)"), std::string(R"(125mmHE)")},
                                                 {std::string(R"(direction)"), double(0.001442)},
                                                 {std::string(R"(range)"), double(5000.000000)}}}},
               {std::string(R"(pitch)"), double(0.000000)},
               {std::string(R"(yaw)"), double(-89.917366)}},
    CSValueMap{{std::string(R"(selfInfo)"),
                CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                   {std::string(R"(damageLevel)"), uint16_t(0)},
                                                                   {std::string(R"(side)"), uint16_t(1)},
                                                                   {std::string(R"(type)"), uint16_t(0)}}},
                           {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(1.049997)},
                                                                   {std::string(R"(y)"), double(0.002507)},
                                                                   {std::string(R"(z)"), double(0.000000)}}},
                           {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.157500)},
                                                                   {std::string(R"(y)"), double(0.000109)},
                                                                   {std::string(R"(z)"), double(-0.000000)}}}}},
               {std::string(R"(scannedInfo)"),
                std::vector<std::any>{
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(1)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.899999)},
                                                                       {std::string(R"(y)"), double(0.001298)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.112500)},
                                                                       {std::string(R"(y)"), double(0.000044)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}},
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(1)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(2)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(0.899999)},
                                                                       {std::string(R"(y)"), double(-0.001298)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(5550.112500)},
                                                                       {std::string(R"(y)"), double(4546.293802)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}}}},
               {std::string(R"(roll)"), double(0.000000)},
               {std::string(R"(weaponinfo)"),
                std::vector<std::any>{CSValueMap{{std::string(R"(ammo)"), int32_t(30)},
                                                 {std::string(R"(reloadingState)"), double(0.000000)},
                                                 {std::string(R"(weaponName)"), std::string(R"(125mmHE)")},
                                                 {std::string(R"(direction)"), double(0.002388)},
                                                 {std::string(R"(range)"), double(5000.000000)}}}},
               {std::string(R"(pitch)"), double(0.000000)},
               {std::string(R"(yaw)"), double(-89.863178)}},
    CSValueMap{{std::string(R"(selfInfo)"),
                CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                   {std::string(R"(damageLevel)"), uint16_t(0)},
                                                                   {std::string(R"(side)"), uint16_t(1)},
                                                                   {std::string(R"(type)"), uint16_t(0)}}},
                           {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(1.199992)},
                                                                   {std::string(R"(y)"), double(0.004412)},
                                                                   {std::string(R"(z)"), double(0.000000)}}},
                           {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.210000)},
                                                                   {std::string(R"(y)"), double(0.000234)},
                                                                   {std::string(R"(z)"), double(-0.000000)}}}}},
               {std::string(R"(scannedInfo)"),
                std::vector<std::any>{
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(0)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(1)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(1.049997)},
                                                                       {std::string(R"(y)"), double(0.002507)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(0.157500)},
                                                                       {std::string(R"(y)"), double(0.000109)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}},
                    CSValueMap{{std::string(R"(baseInfo)"), CSValueMap{{std::string(R"(id)"), uint64_t(1)},
                                                                       {std::string(R"(damageLevel)"), uint16_t(398)},
                                                                       {std::string(R"(side)"), uint16_t(2)},
                                                                       {std::string(R"(type)"), uint16_t(0)}}},
                               {std::string(R"(velocity)"), CSValueMap{{std::string(R"(x)"), double(1.049997)},
                                                                       {std::string(R"(y)"), double(-0.002507)},
                                                                       {std::string(R"(z)"), double(0.000000)}}},
                               {std::string(R"(position)"), CSValueMap{{std::string(R"(x)"), double(5550.157500)},
                                                                       {std::string(R"(y)"), double(4546.293737)},
                                                                       {std::string(R"(z)"), double(-0.000000)}}}}}},
               {std::string(R"(roll)"), double(0.000000)},
               {std::string(R"(weaponinfo)"),
                std::vector<std::any>{CSValueMap{{std::string(R"(ammo)"), int32_t(30)},
                                                 {std::string(R"(reloadingState)"), double(0.000000)},
                                                 {std::string(R"(weaponName)"), std::string(R"(125mmHE)")},
                                                 {std::string(R"(direction)"), double(0.003677)},
                                                 {std::string(R"(range)"), double(5000.000000)}}}},
               {std::string(R"(pitch)"), double(0.000000)},
               {std::string(R"(yaw)"), double(-89.789324)}}};